# Generated by Django 4.0.4 on 2023-01-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='Lecture',
            new_name='lecture',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='Lecture',
            new_name='lecture',
        ),
    ]
